### ISSUE TITLE
Universal path breaks with Dokku deployment.

### ISSUE THREAD

**Issue by almereyda** [TransforMap/transformap-api#32]
When deploying 3dc9564, I recieve 

```
       -----
       module.js:327
           throw err;
           ^
       Error: Cannot find module 'bluebird'
           at Function.Module._resolveFilename (module.js:325:15)
           at Function.Module._load (module.js:276:25)
           at Module.require (module.js:353:17)
           at require (internal/module.js:12:17)
           at Object.<anonymous> (/app/server/lib/promises.js:2:18)
           at Module._compile (module.js:409:26)
           at Object.Module._extensions..js (module.js:416:10)
           at Module.load (module.js:343:32)
           at Function.Module._load (module.js:300:12)
           at Module.require (module.js:353:17)
           at require (internal/module.js:12:17)
           at Object.req [as require] (/app/config/universal_path.js:22:10)
           at Object.<anonymous> (/app/db/init.js:6:22)
           at Module._compile (module.js:409:26)
           at Object.Module._extensions..js (module.js:416:10)
           at Module.load (module.js:343:32)
```

Am trying a more manual deployment approach now.

**Comment by maxlath** [comment]
that make sense:
in [server/lib/promises.js:2](/TransforMap/transformap-api/blob/master/server/lib/promises.js#L2) line 2 (as pointed from the stack trace), we require bluebird:

``` javascript
const bluebird = require('bluebird')
```

but bluebird isn't in [package.json](/TransforMap/transformap-api/blob/master/package.json) dependencies (lines 27 to 36), thus it wasn't installed at deployment.

This can be fixed simply adding bluebird to the dependencies like so:

``` sh
npm install --save bluebird
```

**Comment by almereyda** [comment]
Yes, a4a3682 resolves this.
