### ISSUE TITLE
Install dependencies no longer working

### ISSUE THREAD

**Issue by species** [TransforMap/transformap-api#38]
The current dependencies in package.json throw a lot of errors when trying to install development dependencies.

To the JS demigods, @maxlath any ideas?

npm install --dev output:

```
npm WARN engine grunt-istanbul@0.6.2: wanted: {"node":"~0.12.0"} (current: {"node":"4.6.1","npm":"2.9.0"})
npm WARN peerDependencies The peer dependency jasmine-core@* included from karma-jasmine will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! addLocal Could not install /home/user/data.transformap.co/xo@>=0.16.0 <0.17.0
npm WARN deprecated native-or-bluebird@1.2.0: 'native-or-bluebird' is deprecated. Please use 'any-promise' instead.
npm WARN package.json Dependency 'mocha' exists in both dependencies and devDependencies, using 'mocha@*' from dependencies
npm WARN package.json Dependency 'mocha' exists in both dependencies and devDependencies, using 'mocha@*' from dependencies
npm WARN package.json Dependency 'mocha' exists in both dependencies and devDependencies, using 'mocha@*' from dependencies
npm WARN engine grunt-istanbul@0.6.2: wanted: {"node":"~0.12.0"} (current: {"node":"4.6.1","npm":"2.9.0"})
npm WARN engine grunt-istanbul@0.6.2: wanted: {"node":"~0.12.0"} (current: {"node":"4.6.1","npm":"2.9.0"})
npm WARN package.json Dependency 'mocha' exists in both dependencies and devDependencies, using 'mocha@*' from dependencies
npm WARN package.json Dependency 'mocha' exists in both dependencies and devDependencies, using 'mocha@*' from dependencies
npm WARN package.json Dependency 'mocha' exists in both dependencies and devDependencies, using 'mocha@*' from dependencies
npm WARN engine esfuzz@0.3.1: wanted: {"node":"0.8.x || 0.9.x || 0.10.x"} (current: {"node":"4.6.1","npm":"2.9.0"})
npm ERR! addLocal Could not install /tmp/npm-23187-afd6acf8/git-cache-e57b50b4fdf4/a8dbc872fdb2194bfebdac804b63bd639ef30582
npm WARN peerDependencies The peer dependency eslint-config-standard@* included from eslint-config-standard-deviation--es5 will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency eslint-plugin-promise@* included from eslint-config-standard-deviation--es5 will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency eslint-plugin-standard@* included from eslint-config-standard-deviation--es5 will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency eslint-plugin-standard@^1.1.0 included from eslint-config-standard will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated conventional-changelog@0.2.1: Please update conventional-changelog to >1.0.0. If you are running the cli, use conventional-changelog-cli
npm WARN deprecated babel-core@5.8.23: Babel 5 is no longer being maintained. Upgrade to Babel 6.
npm WARN engine grunt-istanbul@0.6.2: wanted: {"node":"~0.12.0"} (current: {"node":"4.6.1","npm":"2.9.0"})
npm WARN engine grunt-istanbul@0.6.2: wanted: {"node":"~0.12.0"} (current: {"node":"4.6.1","npm":"2.9.0"})
npm WARN package.json Dependency 'shelljs' exists in both dependencies and devDependencies, using 'shelljs@0.1.x' from dependencies
npm WARN peerDependencies The peer dependency eslint-plugin-jsx-a11y@^0.6.2 included from eslint-config-airbnb will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency eslint-plugin-react@^4.3.0 included from eslint-config-airbnb will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN package.json Dependency 'source-map' exists in both dependencies and devDependencies, using 'source-map@~0.1.27' from dependencies
npm WARN package.json Dependency 'source-map' exists in both dependencies and devDependencies, using 'source-map@~0.1.27' from dependencies
npm WARN peerDependencies The peer dependency grunt@~0.4.0 included from grunt-contrib-nodeunit will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN package.json Dependency 'shelljs' exists in both dependencies and devDependencies, using 'shelljs@0.1.x' from dependencies
npm WARN engine grunt-istanbul@0.6.2: wanted: {"node":"~0.12.0"} (current: {"node":"4.6.1","npm":"2.9.0"})
npm WARN engine grunt-istanbul@0.6.2: wanted: {"node":"~0.12.0"} (current: {"node":"4.6.1","npm":"2.9.0"})
npm WARN engine grunt-istanbul@0.6.2: wanted: {"node":"~0.12.0"} (current: {"node":"4.6.1","npm":"2.9.0"})
npm WARN deprecated minimatch@0.4.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN package.json Dependency 'browser-pack' exists in both dependencies and devDependencies, using 'browser-pack@^5.0.1' from dependencies
npm WARN engine grunt-istanbul@0.6.2: wanted: {"node":"~0.12.0"} (current: {"node":"4.6.1","npm":"2.9.0"})
npm WARN peerDependencies The peer dependency sinon@* included from karma-sinon will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN package.json Dependency 'browser-pack' exists in both dependencies and devDependencies, using 'browser-pack@^5.0.1' from dependencies
npm ERR! fetch failed https://registry.npmjs.org/babel-plugin-external-helpers/-/babel-plugin-external-helpers-6.8.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 400
npm ERR! Linux 4.7.0-0.bpo.1-amd64
npm ERR! argv "/home/user/.nvm/versions/node/v4.6.1/bin/node" "/usr/local/bin/npm" "install" "--dev"
npm ERR! node v4.6.1
npm ERR! npm  v2.9.0

npm ERR! Cannot read property 'dependencies' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.7.0-0.bpo.1-amd64
npm ERR! argv "/home/user/.nvm/versions/node/v4.6.1/bin/node" "/usr/local/bin/npm" "install" "--dev"
npm ERR! node v4.6.1
npm ERR! npm  v2.9.0

npm ERR! Cannot read property 'dependencies' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.7.0-0.bpo.1-amd64
npm ERR! argv "/home/user/.nvm/versions/node/v4.6.1/bin/node" "/usr/local/bin/npm" "install" "--dev"
npm ERR! node v4.6.1
npm ERR! npm  v2.9.0

npm ERR! Cannot read property 'dependencies' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! unpack Could not read data for nopt@1.0.10
npm ERR! unpack Could not read data for resolve@0.3.1
npm ERR! unpack Could not read data for findup-sync@0.1.3
npm ERR! unpack Could not read data for grunt-contrib-nodeunit@0.4.1
npm ERR! unpack Could not read data for rimraf@2.2.8
npm ERR! unpack Could not read data for path-is-absolute@1.0.1
npm ERR! unpack Could not read data for grunt-contrib-watch@1.0.0
npm ERR! unpack Could not read data for dateformat@1.0.12
npm ERR! unpack Could not read data for semver@2.1.0
npm ERR! unpack Could not read data for grunt-cli@1.2.0
npm ERR! unpack Could not read data for coffee-script@1.10.0
npm ERR! unpack Could not read data for glob@7.0.6
npm ERR! unpack Could not read data for shelljs@0.5.3
npm ERR! unpack Could not read data for grunt-contrib-jshint@1.0.0
npm ERR! unpack Could not read data for findup-sync@0.3.0
npm ERR! unpack Could not read data for js-yaml@3.5.5
npm ERR! unpack Could not read data for eventemitter2@0.4.14
npm ERR! unpack Could not read data for temporary@0.0.8
npm ERR! unpack Could not read data for exit@0.1.2
npm ERR! unpack Could not read data for through2@2.0.1
npm ERR! unpack Could not read data for grunt-known-options@1.1.0
npm ERR! unpack Could not read data for iconv-lite@0.4.13
npm ERR! unpack Could not read data for grunt-jscs@2.8.0
npm ERR! unpack Could not read data for grunt-legacy-log@1.0.0
npm ERR! unpack Could not read data for grunt-legacy-util@1.0.0
npm ERR! unpack Could not read data for difflet@0.2.6
npm ERR! unpack Could not read data for nopt@3.0.6
npm WARN engine grunt-istanbul@0.6.2: wanted: {"node":"~0.12.0"} (current: {"node":"4.6.1","npm":"2.9.0"})
npm ERR! Linux 4.7.0-0.bpo.1-amd64
npm ERR! argv "/home/user/.nvm/versions/node/v4.6.1/bin/node" "/usr/local/bin/npm" "install" "--dev"
npm ERR! node v4.6.1
npm ERR! npm  v2.9.0

npm ERR! Cannot read property 'dependencies' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.7.0-0.bpo.1-amd64
npm ERR! argv "/home/user/.nvm/versions/node/v4.6.1/bin/node" "/usr/local/bin/npm" "install" "--dev"
npm ERR! node v4.6.1
npm ERR! npm  v2.9.0

npm ERR! Cannot read property 'dependencies' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! unpack Could not read data for clean-yaml-object@0.1.0
npm ERR! unpack Could not read data for isexe@1.1.2
npm ERR! unpack Could not read data for stack-utils@0.4.0
npm ERR! unpack Could not read data for tap-parser@1.3.2
npm ERR! unpack Could not read data for glob@7.1.1
npm ERR! unpack Could not read data for standard@7.1.2
npm ERR! unpack Could not read data for coveralls@2.11.14
npm ERR! unpack Could not read data for readable-stream@2.1.5
npm ERR! unpack Could not read data for codecov.io@0.1.6
npm ERR! unpack Could not read data for signal-exit@2.1.2
npm ERR! unpack Could not read data for supports-color@1.3.1
npm ERR! unpack Could not read data for deeper@2.1.0
npm ERR! unpack Could not read data for only-shallow@1.2.0
npm ERR! unpack Could not read data for tmatch@2.0.1
npm ERR! unpack Could not read data for foreground-child@1.5.3
npm ERR! unpack Could not read data for tap-mocha-reporter@0.0.27
npm ERR! unpack Could not read data for opener@1.4.2
npm ERR! unpack Could not read data for which@1.2.11
npm ERR! unpack Could not read data for js-yaml@3.6.1
npm ERR! unpack Could not read data for nyc@6.6.1
npm ERR! unpack Could not read data for grunt-release@0.13.1
npm ERR! unpack Could not read data for should@7.1.1
npm ERR! unpack Could not read data for grunt-mdlint@0.0.1
npm ERR! unpack Could not read data for matchdep@1.0.1
npm ERR! unpack Could not read data for ctrlflow@0.0.3
npm ERR! unpack Could not read data for test-cmd@1.7.0
npm ERR! unpack Could not read data for rimraf@2.2.8
npm ERR! unpack Could not read data for mocha@1.17.1
npm ERR! unpack Could not read data for glob@3.2.11
npm ERR! unpack Could not read data for jshint@2.4.4
npm ERR! unpack Could not read data for rewire@2.0.1
npm ERR! unpack Could not read data for chai@1.8.1
npm ERR! unpack Could not read data for bench-it@0.1.0
npm ERR! unpack Could not read data for coffeelint-use-strict@0.0.1
npm ERR! unpack Could not read data for bluebird@3.4.6
npm ERR! unpack Could not read data for coffeelint@1.16.0
npm ERR! unpack Could not read data for exit@0.1.2
npm ERR! unpack Could not read data for iconv-lite@0.2.11
npm ERR! unpack Could not read data for grunt-legacy-log@0.1.3
npm ERR! unpack Could not read data for grunt-legacy-util@0.2.0
npm ERR! unpack Could not read data for difflet@0.2.6
npm ERR! unpack Could not read data for nopt@1.0.10
npm ERR! unpack Could not read data for getobject@0.1.0
npm ERR! unpack Could not read data for chai@2.3.0
npm ERR! unpack Could not read data for bluebird@2.11.0
npm ERR! unpack Could not read data for hash_file@0.1.1
npm ERR! unpack Could not read data for tape@4.4.0
npm ERR! unpack Could not read data for readable-stream@1.0.34
npm ERR! unpack Could not read data for grunt-legacy-log@0.1.3
npm ERR! unpack Could not read data for difflet@0.2.6
npm ERR! unpack Could not read data for inherits@2.0.3
npm ERR! unpack Could not read data for typedarray@0.0.6
npm ERR! unpack Could not read data for readable-stream@2.0.6
npm ERR! unpack Could not read data for tape@2.3.3
npm ERR! unpack Could not read data for glob@7.1.1
npm ERR! unpack Could not read data for benchmarked@0.1.5
npm ERR! unpack Could not read data for repeating@2.0.1
npm ERR! unpack Could not read data for chai@1.7.2
npm ERR! unpack Could not read data for grunt-simple-mocha@0.4.1
npm ERR! unpack Could not read data for grunt-bump@0.0.17
npm ERR! unpack Could not read data for grunt-auto-release@0.0.6
npm ERR! unpack Could not read data for grunt-bump@0.0.17
npm ERR! unpack Could not read data for from@0.1.3
npm ERR! unpack Could not read data for stream-spec@0.3.6
npm ERR! unpack Could not read data for it-is@1.0.3
npm ERR! unpack Could not read data for ubelt@3.2.2
npm ERR! unpack Could not read data for asynct@1.1.0
npm ERR! unpack Could not read data for split@0.3.3
npm ERR! unpack Could not read data for pause-stream@0.0.11
npm ERR! unpack Could not read data for duplexer@0.1.1
npm ERR! unpack Could not read data for stream-combiner@0.0.4
npm ERR! unpack Could not read data for through@2.3.8
npm ERR! unpack Could not read data for map-stream@0.1.0
npm ERR! unpack Could not read data for is-obj@1.0.1
npm ERR! unpack Could not read data for is-obj@1.0.1
npm ERR! unpack Could not read data for is-obj@1.0.1
npm ERR! unpack Could not read data for is-obj@1.0.1
npm ERR! unpack Could not read data for is-obj@1.0.1
npm ERR! unpack Could not read data for is-obj@1.0.1
npm ERR! unpack Could not read data for is-obj@1.0.1
npm ERR! unpack Could not read data for request@2.47.0
npm ERR! unpack Could not read data for async@2.1.2
npm ERR! unpack Could not read data for iconv@2.1.11
npm ERR! unpack Could not read data for unorm@1.4.1
npm ERR! unpack Could not read data for errto@0.2.1
npm WARN package.json Dependency 'mocha' exists in both dependencies and devDependencies, using 'mocha@*' from dependencies
npm WARN package.json Dependency 'mocha' exists in both dependencies and devDependencies, using 'mocha@*' from dependencies
npm ERR! unpack Could not read data for mock-fs@2.7.1
npm ERR! unpack Could not read data for dateformat@1.0.12
npm ERR! unpack Could not read data for semver@5.3.0
npm ERR! unpack Could not read data for q@1.4.1
npm ERR! unpack Could not read data for github-remove-all-releases@1.0.1
npm ERR! unpack Could not read data for jshint@2.9.4
npm ERR! unpack Could not read data for shelljs@0.5.3
npm ERR! unpack Could not read data for github@0.2.4
npm ERR! unpack Could not read data for git-semver-tags@1.1.2
npm ERR! unpack Could not read data for lodash.merge@4.6.0
npm ERR! unpack Could not read data for grunt-contrib-nodeunit@0.2.2
npm ERR! unpack Could not read data for which@1.0.9
npm ERR! unpack Could not read data for dateformat@1.0.2-1.2.3
npm ERR! unpack Could not read data for async@0.1.22
npm ERR! unpack Could not read data for colors@0.6.2
npm ERR! unpack Could not read data for rimraf@2.2.8
npm ERR! unpack Could not read data for semver@2.1.0
npm ERR! unpack Could not read data for coffee-script@1.3.3
npm ERR! unpack Could not read data for underscore.string@2.2.1
npm ERR! unpack Could not read data for grunt-contrib-watch@0.5.3
npm ERR! unpack Could not read data for hooker@0.2.3
npm ERR! unpack Could not read data for shelljs@0.2.6
npm ERR! unpack Could not read data for glob@3.1.21
npm ERR! unpack Could not read data for grunt-contrib-jshint@0.6.5
npm [1]    23187 abort      npm install --dev
^[npm install --dev  1750.72s user 83.83s system 112% cpu 27:09.37 total
```

**Comment by maxlath** [comment]
ahah flattered ;) can't reproduce unfortunately.
I would recommend installing the latest node v6 (which should come with npm v3, or now even v4), as many warning mention npm v3+

Luckily, you are using [nvm](https://github.com/creationix/nvm) so that should be quite easy:

```
$ nvm install 6 && nvm use 6
$ exit
```

(reopen)

```
$ nvm current
```

should return v6.x.x, if not, see in your .bashrc/.zshrc/.profile files if something triggers a version in particular.

Then

```
cd path/to/this/project
rm -rf node_modules
npm install
```

Can you try that and tell us how it goes?

**Comment by species** [comment]
Thanks, npm install now works without an error...

But, now `npm start` fails:

```
> transformap-api@1.0.0 prestart /home/user/data.transformap.co
> node ./db/prestart.js


/home/user/data.transformap.co/db/prestart.js:7
const wrap = (el) => `"${el}"`
                   ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

npm ERR! Linux 4.7.0-0.bpo.1-amd64
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.38
npm ERR! npm  v2.9.0
npm ERR! code ELIFECYCLE
npm ERR! transformap-api@1.0.0 prestart: `node ./db/prestart.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the transformap-api@1.0.0 prestart script 'node ./db/prestart.js'.
npm ERR! This is most likely a problem with the transformap-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./db/prestart.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls transformap-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/data.transformap.co/npm-debug.log
```

The error looks weird to me: did the syntax of JS change in node 6?

**Comment by maxlath** [comment]
no, its that your [NVM](https://github.com/creationix/nvm) environment isn't working properly here, so you're back to your `apt-get install`ed node executable I guess:

```
npm ERR! node v0.10.38
npm ERR! npm  v2.9.0
```

Node v0.10 knows very little about ES6, thus its ignorance of arrow functions.

To fix NVM, make sure that those two lines

```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
```

are in one of `~/.bash_profile`, `~/.zshrc`, `~/.profile`, or `~/.bashrc`

You may also run `nvm alias default 6`

**Comment by thoka** [comment]
You seem to run node 0.10.38, not 6 ...

Am 24.10.2016 16:34 schrieb "Michael Maier" notifications@github.com:

**Comment by species** [comment]
Thanks for all the hints!

After a three-day-Odyssee with setting up CouchDB on Debian, I can confirm it works as expected ☺.
